# profile active
spring:
  profiles:
    active: local
    include: core

---

# local profile
spring:
  profiles: local
  config:
    use-legacy-processing: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8091

web:
  address: "http://localhost:8091"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
