# local
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.minikube.internal:3306/digimon_pg?serverTimezone=UTC
    username: root
    password: tmdgns2

server:
  error:
    whitelabel:
      enabled: false
  port: 8091

web:
  address: "http://localhost:8091"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: error

mybatis:
  mapper-locations: classpath:mapper/*.xml
